# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApiProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ApiProject
  pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'
    pod 'SDWebImage'
    

  target 'ApiProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApiProjectUITests' do
    # Pods for testing
  end

end
